import Vue from 'vue'

// 按需导入
// 导入弹框提示组件 Message
import {Button,Form,FormItem,Input,Message,Container,Header,Aside,Main,Menu,MenuItem,MenuItemGroup,Submenu,Breadcrumb,BreadcrumbItem,Card,Row,Col,Table,TableColumn,Switch,Tooltip,Pagination,Dialog,RadioGroup,Radio,Select,Option,Tag,RadioButton,Checkbox,CheckboxGroup,Divider,Popover,Tree,Notification,Upload,Loading,Collapse,CollapseItem,Badge} from 'element-ui'

Vue.prototype.$message = Message
// 全局可用
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Button)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Select)
Vue.use(Option)
Vue.use(Tag)
Vue.use(RadioButton)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Divider)
Vue.use(Popover)
Vue.use(Tree)
Vue.use(Notification)
Vue.use(Upload)
Vue.use(Loading)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Badge)